### ISSUE TITLE
Home button

### ISSUE THREAD

**Issue by grundok** [Shoko84/FightSabers#1]
When i go into the Fight Saber settings and try to go back to home it wont work for me

**Comment by Shoko84** [comment]
Do you mean the bottom `Home` button? Yes because uh you're already on the FightSabers home page already. There is only one page for now, the other ones are in WIP.

If you want to close the FightSabers page, just click again the floating button above the experience bar 👍

**Comment by grundok** [comment]
Thx, figured it out myself and felt like an idiot after that
